// Datos iniciales extraídos del PDF para seedear la base de datos

export const companiasSemilla = [
  {
    nombre: "Seguros Pirámides",
    col_suma_salud: "Desde $1,000 hasta $50,000",
    col_deducible: "$0",
    col_maternidad: "Opcional",
    col_suma_maternidad: "-",
    col_cobertura_inmediata: "Hasta $5,000",
    col_examenes: "No",
    col_espera_inicial: "No aplican para grupo inicial",
    col_cantidad_minima: "A partir de 50 Titulares",
    col_admisibilidad: "Sin límite de edad",
    col_preexistencias: "Reconocidas",
    col_admisibilidad_nuevas: "Hasta 75 años de edad",
    col_preexistencias_nuevas: "Reconocidas, con plazos de espera",
    col_espera_nuevas: "9 meses",
    col_cobertura_geografica: "Venezuela",
    col_asistencia_internacional: "Opcional",
    col_condiciones_pago: "Contado / Semestral / Trimestral",
    
    ind_admisibilidad: "Hasta 69 años",
    ind_suma_salud: "Desde $5,000 hasta $200,000",
    ind_deducible: "$0",
    ind_maternidad: "Opcional",
    ind_deducible_maternidad: "Desde $1,000 hasta $3,000",
    ind_asistencia_internacional: "Disponible para > $50.000",
    ind_espera_exterior: "Si toman Asist Intl, no aplican",
    ind_examenes: "No",
    ind_espera_vzla: "9 meses",
    ind_condiciones_pago: "Contado / Semestral / Trimestral"
  },
  {
    nombre: "Seguros Hispanas",
    col_suma_salud: "Desde $2,000 hasta $30,000",
    col_deducible: "$0",
    col_maternidad: "Opcional",
    col_suma_maternidad: "$1,000",
    col_cobertura_inmediata: "-",
    col_examenes: "No",
    col_espera_inicial: "No aplican para grupo inicial",
    col_cantidad_minima: "A partir de 15 Titulares",
    col_admisibilidad: "Sin límite de edad",
    col_preexistencias: "Condicionado",
    col_admisibilidad_nuevas: "Sin límite de edad",
    col_preexistencias_nuevas: "Condicionado",
    col_espera_nuevas: "9 meses",
    col_cobertura_geografica: "Venezuela",
    col_asistencia_internacional: "Opcional",
    col_condiciones_pago: "Contado",
    
    ind_admisibilidad: "Hasta 69 años",
    ind_suma_salud: "Desde $5,000 hasta $50,000",
    ind_deducible: "$0",
    ind_maternidad: "Opcional",
    ind_deducible_maternidad: "$3,000",
    ind_asistencia_internacional: "Opcional",
    ind_espera_exterior: "Aplican",
    ind_examenes: "Si, a partir de 54 años",
    ind_espera_vzla: "10 meses",
    ind_condiciones_pago: "Contado"
  },
  {
    nombre: "Mercantil Seguros",
    col_suma_salud: "A partir de $3,000",
    col_deducible: "$0",
    col_maternidad: "Incluida",
    col_suma_maternidad: "$1,000",
    col_cobertura_inmediata: "Hasta $2,000",
    col_examenes: "No",
    col_espera_inicial: "No aplican para grupo inicial",
    col_cantidad_minima: "A partir de 5 Titulares",
    col_admisibilidad: "Sin límite de edad",
    col_preexistencias: "Reconocidas con plazos de espera",
    col_admisibilidad_nuevas: "Hasta 74 años de edad",
    col_preexistencias_nuevas: "Reconocidas con plazos de espera",
    col_espera_nuevas: "9 meses",
    col_cobertura_geografica: "Venezuela",
    col_asistencia_internacional: "Incluida",
    col_condiciones_pago: "Contado / 40% + 6 cuotas",
    
    ind_admisibilidad: "Hasta 74 años",
    ind_suma_salud: "A partir de $3,000",
    ind_deducible: "$0",
    ind_maternidad: "Opcional",
    ind_deducible_maternidad: "$3,000",
    ind_asistencia_internacional: "Opcional",
    ind_espera_exterior: "Aplican",
    ind_examenes: "Si, a partir de 60 años",
    ind_espera_vzla: "9 meses",
    ind_condiciones_pago: "Contado / 40% + 6 cuotas"
  },
  {
    nombre: "Universitas Seguros",
    col_suma_salud: "Desde $5,000 hasta $200,000",
    col_deducible: "$0",
    col_maternidad: "Incluida",
    col_suma_maternidad: "$500",
    col_cobertura_inmediata: "Total Suma Asegurada",
    col_examenes: "No",
    col_espera_inicial: "9 meses",
    col_cantidad_minima: "A partir de 15 Titulares",
    col_admisibilidad: "Sin límite de edad",
    col_preexistencias: "-",
    col_admisibilidad_nuevas: "Hasta 75 años de edad",
    col_preexistencias_nuevas: "Reconocidas, con plazos de espera",
    col_espera_nuevas: "9 meses",
    col_cobertura_geografica: "Venezuela",
    col_asistencia_internacional: "Incluida",
    col_condiciones_pago: "Contado / Semestral / Trimestral",
    
    ind_admisibilidad: "Hasta 75 años",
    ind_suma_salud: "Desde $15,000 hasta $200,000",
    ind_deducible: "$0",
    ind_maternidad: "Opcional",
    ind_deducible_maternidad: "Desde $3,000 hasta $10,000",
    ind_asistencia_internacional: "Opcional",
    ind_espera_exterior: "Aplican",
    ind_examenes: "Si, a partir de 54 años",
    ind_espera_vzla: "9 meses",
    ind_condiciones_pago: "Contado / Semestral / Trimestral"
  },
  {
    nombre: "Seguros Caracas",
    col_suma_salud: "A partir de $5,000",
    col_deducible: "$0",
    col_maternidad: "Incluida",
    col_suma_maternidad: "$2,000",
    col_cobertura_inmediata: "Total Suma Asegurada",
    col_examenes: "No",
    col_espera_inicial: "No aplican para grupo inicial",
    col_cantidad_minima: "A partir de 50 titulares",
    col_admisibilidad: "Hasta 79 años de edad",
    col_preexistencias: "Hasta 79 años de edad",
    col_admisibilidad_nuevas: "Hasta 79 años de edad",
    col_preexistencias_nuevas: "Hasta 79 años de edad",
    col_espera_nuevas: "9 meses",
    col_cobertura_geografica: "Venezuela",
    col_asistencia_internacional: "Opcional",
    col_condiciones_pago: "Contado / Semestral / Cuatrimestral",
    
    ind_admisibilidad: "Hasta 79 años de edad",
    ind_suma_salud: "A partir de $3,000",
    ind_deducible: "$0",
    ind_maternidad: "Opcional",
    ind_deducible_maternidad: "$0",
    ind_asistencia_internacional: "Opcional",
    ind_espera_exterior: "Aplican",
    ind_examenes: "Si, a partir de 54 años",
    ind_espera_vzla: "9 meses",
    ind_condiciones_pago: "Contado / Semestral / Cuatrimestral"
  },
  {
    nombre: "La Occidental de Seguros",
    col_suma_salud: "A partir de $5,000",
    col_deducible: "$0",
    col_maternidad: "Incluida",
    col_suma_maternidad: "$1,000",
    col_cobertura_inmediata: "-",
    col_examenes: "No",
    col_espera_inicial: "-",
    col_cantidad_minima: "A partir de 50 titulares",
    col_admisibilidad: "Sin límite de edad",
    col_preexistencias: "Sin límite de edad",
    col_admisibilidad_nuevas: "Sin límite de edad",
    col_preexistencias_nuevas: "Sin límite de edad",
    col_espera_nuevas: "9 meses",
    col_cobertura_geografica: "Venezuela",
    col_asistencia_internacional: "No",
    col_condiciones_pago: "Contado",
    
    ind_admisibilidad: "Sin límite de edad",
    ind_suma_salud: "A partir de $3,000",
    ind_deducible: "$0",
    ind_maternidad: "Opcional",
    ind_deducible_maternidad: "$0",
    ind_asistencia_internacional: "Opcional",
    ind_espera_exterior: "Aplican",
    ind_examenes: "Si, a partir de 54 años",
    ind_espera_vzla: "9 meses",
    ind_condiciones_pago: "Contado"
  }
];

// Tarifas anuales
export const tarifasSemilla = [
  // 1. COLECTIVOS
  // Seguros Pirámides - Colectivo ($5,000 Suma Asegurada)
  { compania: "Seguros Pirámides", tipo_cobertura: "colectivo", edad_min: 0, edad_max: 9, suma_asegurada: 5000, prima: 207 },
  { compania: "Seguros Pirámides", tipo_cobertura: "colectivo", edad_min: 10, edad_max: 17, suma_asegurada: 5000, prima: 223 },
  { compania: "Seguros Pirámides", tipo_cobertura: "colectivo", edad_min: 18, edad_max: 29, suma_asegurada: 5000, prima: 237 },
  { compania: "Seguros Pirámides", tipo_cobertura: "colectivo", edad_min: 30, edad_max: 39, suma_asegurada: 5000, prima: 260 },
  { compania: "Seguros Pirámides", tipo_cobertura: "colectivo", edad_min: 40, edad_max: 49, suma_asegurada: 5000, prima: 279 },
  { compania: "Seguros Pirámides", tipo_cobertura: "colectivo", edad_min: 50, edad_max: 54, suma_asegurada: 5000, prima: 312 },
  { compania: "Seguros Pirámides", tipo_cobertura: "colectivo", edad_min: 55, edad_max: 59, suma_asegurada: 5000, prima: 360 },
  { compania: "Seguros Pirámides", tipo_cobertura: "colectivo", edad_min: 60, edad_max: 65, suma_asegurada: 5000, prima: 400 },
  { compania: "Seguros Pirámides", tipo_cobertura: "colectivo", edad_min: 66, edad_max: 69, suma_asegurada: 5000, prima: 400 },
  { compania: "Seguros Pirámides", tipo_cobertura: "colectivo", edad_min: 70, edad_max: 79, suma_asegurada: 5000, prima: 466 },
  { compania: "Seguros Pirámides", tipo_cobertura: "colectivo", edad_min: 80, edad_max: 89, suma_asegurada: 5000, prima: 570 },

  // Universitas Seguros - Colectivo ($5,000 Suma Asegurada)
  { compania: "Universitas Seguros", tipo_cobertura: "colectivo", edad_min: 0, edad_max: 9, suma_asegurada: 5000, prima: 159 },
  { compania: "Universitas Seguros", tipo_cobertura: "colectivo", edad_min: 10, edad_max: 17, suma_asegurada: 5000, prima: 178 },
  { compania: "Universitas Seguros", tipo_cobertura: "colectivo", edad_min: 18, edad_max: 29, suma_asegurada: 5000, prima: 194 },
  { compania: "Universitas Seguros", tipo_cobertura: "colectivo", edad_min: 30, edad_max: 39, suma_asegurada: 5000, prima: 228 },
  { compania: "Universitas Seguros", tipo_cobertura: "colectivo", edad_min: 40, edad_max: 49, suma_asegurada: 5000, prima: 255 },
  { compania: "Universitas Seguros", tipo_cobertura: "colectivo", edad_min: 50, edad_max: 54, suma_asegurada: 5000, prima: 303 },
  { compania: "Universitas Seguros", tipo_cobertura: "colectivo", edad_min: 55, edad_max: 59, suma_asegurada: 5000, prima: 369 },
  { compania: "Universitas Seguros", tipo_cobertura: "colectivo", edad_min: 60, edad_max: 65, suma_asegurada: 5000, prima: 505 },
  { compania: "Universitas Seguros", tipo_cobertura: "colectivo", edad_min: 66, edad_max: 69, suma_asegurada: 5000, prima: 505 },
  { compania: "Universitas Seguros", tipo_cobertura: "colectivo", edad_min: 70, edad_max: 79, suma_asegurada: 5000, prima: 605 },
  { compania: "Universitas Seguros", tipo_cobertura: "colectivo", edad_min: 80, edad_max: 89, suma_asegurada: 5000, prima: 751 },

  // La Occidental de Seguros - Colectivo ($5,000 Suma Asegurada)
  { compania: "La Occidental de Seguros", tipo_cobertura: "colectivo", edad_min: 0, edad_max: 9, suma_asegurada: 5000, prima: 110 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "colectivo", edad_min: 10, edad_max: 17, suma_asegurada: 5000, prima: 117 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "colectivo", edad_min: 18, edad_max: 29, suma_asegurada: 5000, prima: 156 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "colectivo", edad_min: 30, edad_max: 39, suma_asegurada: 5000, prima: 195 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "colectivo", edad_min: 40, edad_max: 49, suma_asegurada: 5000, prima: 250 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "colectivo", edad_min: 50, edad_max: 54, suma_asegurada: 5000, prima: 297 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "colectivo", edad_min: 55, edad_max: 59, suma_asegurada: 5000, prima: 332 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "colectivo", edad_min: 60, edad_max: 65, suma_asegurada: 5000, prima: 493 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "colectivo", edad_min: 66, edad_max: 69, suma_asegurada: 5000, prima: 493 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "colectivo", edad_min: 70, edad_max: 79, suma_asegurada: 5000, prima: 578 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "colectivo", edad_min: 80, edad_max: 89, suma_asegurada: 5000, prima: 789 },

  // Mercantil Seguros - Colectivo ($5,000 Suma Asegurada)
  { compania: "Mercantil Seguros", tipo_cobertura: "colectivo", edad_min: 0, edad_max: 17, suma_asegurada: 5000, prima: 180 }, // estimación para cubrir menores
  { compania: "Mercantil Seguros", tipo_cobertura: "colectivo", edad_min: 18, edad_max: 29, suma_asegurada: 5000, prima: 202 },
  { compania: "Mercantil Seguros", tipo_cobertura: "colectivo", edad_min: 30, edad_max: 39, suma_asegurada: 5000, prima: 202 },
  { compania: "Mercantil Seguros", tipo_cobertura: "colectivo", edad_min: 40, edad_max: 49, suma_asegurada: 5000, prima: 202 },
  { compania: "Mercantil Seguros", tipo_cobertura: "colectivo", edad_min: 50, edad_max: 54, suma_asegurada: 5000, prima: 202 },
  { compania: "Mercantil Seguros", tipo_cobertura: "colectivo", edad_min: 55, edad_max: 59, suma_asegurada: 5000, prima: 202 },
  { compania: "Mercantil Seguros", tipo_cobertura: "colectivo", edad_min: 60, edad_max: 65, suma_asegurada: 5000, prima: 202 },
  { compania: "Mercantil Seguros", tipo_cobertura: "colectivo", edad_min: 66, edad_max: 79, suma_asegurada: 5000, prima: 350 }, // estimación
  { compania: "Mercantil Seguros", tipo_cobertura: "colectivo", edad_min: 80, edad_max: 89, suma_asegurada: 5000, prima: 500 }, // estimación

  // Seguros Caracas - Colectivo (Estimaciones o valores base de referencia similares)
  { compania: "Seguros Caracas", tipo_cobertura: "colectivo", edad_min: 0, edad_max: 9, suma_asegurada: 5000, prima: 190 },
  { compania: "Seguros Caracas", tipo_cobertura: "colectivo", edad_min: 10, edad_max: 17, suma_asegurada: 5000, prima: 205 },
  { compania: "Seguros Caracas", tipo_cobertura: "colectivo", edad_min: 18, edad_max: 29, suma_asegurada: 5000, prima: 220 },
  { compania: "Seguros Caracas", tipo_cobertura: "colectivo", edad_min: 30, edad_max: 39, suma_asegurada: 5000, prima: 245 },
  { compania: "Seguros Caracas", tipo_cobertura: "colectivo", edad_min: 40, edad_max: 49, suma_asegurada: 5000, prima: 265 },
  { compania: "Seguros Caracas", tipo_cobertura: "colectivo", edad_min: 50, edad_max: 54, suma_asegurada: 5000, prima: 300 },
  { compania: "Seguros Caracas", tipo_cobertura: "colectivo", edad_min: 55, edad_max: 59, suma_asegurada: 5000, prima: 355 },
  { compania: "Seguros Caracas", tipo_cobertura: "colectivo", edad_min: 60, edad_max: 65, suma_asegurada: 5000, prima: 450 },
  { compania: "Seguros Caracas", tipo_cobertura: "colectivo", edad_min: 66, edad_max: 69, suma_asegurada: 5000, prima: 450 },
  { compania: "Seguros Caracas", tipo_cobertura: "colectivo", edad_min: 70, edad_max: 79, suma_asegurada: 5000, prima: 540 },
  { compania: "Seguros Caracas", tipo_cobertura: "colectivo", edad_min: 80, edad_max: 89, suma_asegurada: 5000, prima: 700 },

  // Seguros Hispanas - Colectivo
  { compania: "Seguros Hispanas", tipo_cobertura: "colectivo", edad_min: 0, edad_max: 9, suma_asegurada: 5000, prima: 180 },
  { compania: "Seguros Hispanas", tipo_cobertura: "colectivo", edad_min: 10, edad_max: 17, suma_asegurada: 5000, prima: 195 },
  { compania: "Seguros Hispanas", tipo_cobertura: "colectivo", edad_min: 18, edad_max: 29, suma_asegurada: 5000, prima: 210 },
  { compania: "Seguros Hispanas", tipo_cobertura: "colectivo", edad_min: 30, edad_max: 39, suma_asegurada: 5000, prima: 235 },
  { compania: "Seguros Hispanas", tipo_cobertura: "colectivo", edad_min: 40, edad_max: 49, suma_asegurada: 5000, prima: 250 },
  { compania: "Seguros Hispanas", tipo_cobertura: "colectivo", edad_min: 50, edad_max: 54, suma_asegurada: 5000, prima: 290 },
  { compania: "Seguros Hispanas", tipo_cobertura: "colectivo", edad_min: 55, edad_max: 59, suma_asegurada: 5000, prima: 340 },
  { compania: "Seguros Hispanas", tipo_cobertura: "colectivo", edad_min: 60, edad_max: 65, suma_asegurada: 5000, prima: 430 },
  { compania: "Seguros Hispanas", tipo_cobertura: "colectivo", edad_min: 66, edad_max: 69, suma_asegurada: 5000, prima: 430 },
  { compania: "Seguros Hispanas", tipo_cobertura: "colectivo", edad_min: 70, edad_max: 79, suma_asegurada: 5000, prima: 520 },
  { compania: "Seguros Hispanas", tipo_cobertura: "colectivo", edad_min: 80, edad_max: 89, suma_asegurada: 5000, prima: 680 },

  // 2. INDIVIDUALES
  // Seguros Pirámides - Individual (Suma Asegurada $5,000)
  { compania: "Seguros Pirámides", tipo_cobertura: "individual", edad_min: 0, edad_max: 17, suma_asegurada: 5000, prima: 257 },
  { compania: "Seguros Pirámides", tipo_cobertura: "individual", edad_min: 18, edad_max: 29, suma_asegurada: 5000, prima: 257 },
  { compania: "Seguros Pirámides", tipo_cobertura: "individual", edad_min: 30, edad_max: 39, suma_asegurada: 5000, prima: 257 },
  { compania: "Seguros Pirámides", tipo_cobertura: "individual", edad_min: 40, edad_max: 49, suma_asegurada: 5000, prima: 270 }, // aproximado
  { compania: "Seguros Pirámides", tipo_cobertura: "individual", edad_min: 50, edad_max: 59, suma_asegurada: 5000, prima: 280 }, // aproximado
  { compania: "Seguros Pirámides", tipo_cobertura: "individual", edad_min: 60, edad_max: 65, suma_asegurada: 5000, prima: 292 },
  { compania: "Seguros Pirámides", tipo_cobertura: "individual", edad_min: 66, edad_max: 89, suma_asegurada: 5000, prima: 292 },

  // Mercantil Seguros - Individual (Suma Asegurada $200,000 según ejemplo)
  { compania: "Mercantil Seguros", tipo_cobertura: "individual", edad_min: 0, edad_max: 17, suma_asegurada: 200000, prima: 413 },
  { compania: "Mercantil Seguros", tipo_cobertura: "individual", edad_min: 18, edad_max: 29, suma_asegurada: 200000, prima: 413 },
  { compania: "Mercantil Seguros", tipo_cobertura: "individual", edad_min: 30, edad_max: 39, suma_asegurada: 200000, prima: 413 },
  { compania: "Mercantil Seguros", tipo_cobertura: "individual", edad_min: 40, edad_max: 49, suma_asegurada: 200000, prima: 500 }, // aproximado
  { compania: "Mercantil Seguros", tipo_cobertura: "individual", edad_min: 50, edad_max: 59, suma_asegurada: 200000, prima: 550 }, // aproximado
  { compania: "Mercantil Seguros", tipo_cobertura: "individual", edad_min: 60, edad_max: 65, suma_asegurada: 200000, prima: 591 },
  { compania: "Mercantil Seguros", tipo_cobertura: "individual", edad_min: 66, edad_max: 89, suma_asegurada: 200000, prima: 591 },

  // Universitas Seguros - Individual (Estimado similar)
  { compania: "Universitas Seguros", tipo_cobertura: "individual", edad_min: 0, edad_max: 17, suma_asegurada: 5000, prima: 250 },
  { compania: "Universitas Seguros", tipo_cobertura: "individual", edad_min: 18, edad_max: 29, suma_asegurada: 5000, prima: 250 },
  { compania: "Universitas Seguros", tipo_cobertura: "individual", edad_min: 30, edad_max: 39, suma_asegurada: 5000, prima: 250 },
  { compania: "Universitas Seguros", tipo_cobertura: "individual", edad_min: 40, edad_max: 49, suma_asegurada: 5000, prima: 260 },
  { compania: "Universitas Seguros", tipo_cobertura: "individual", edad_min: 50, edad_max: 59, suma_asegurada: 5000, prima: 275 },
  { compania: "Universitas Seguros", tipo_cobertura: "individual", edad_min: 60, edad_max: 65, suma_asegurada: 5000, prima: 285 },
  { compania: "Universitas Seguros", tipo_cobertura: "individual", edad_min: 66, edad_max: 89, suma_asegurada: 5000, prima: 285 },

  // La Occidental de Seguros - Individual
  { compania: "La Occidental de Seguros", tipo_cobertura: "individual", edad_min: 0, edad_max: 17, suma_asegurada: 5000, prima: 240 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "individual", edad_min: 18, edad_max: 29, suma_asegurada: 5000, prima: 240 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "individual", edad_min: 30, edad_max: 39, suma_asegurada: 5000, prima: 240 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "individual", edad_min: 40, edad_max: 49, suma_asegurada: 5000, prima: 250 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "individual", edad_min: 50, edad_max: 59, suma_asegurada: 5000, prima: 260 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "individual", edad_min: 60, edad_max: 65, suma_asegurada: 5000, prima: 275 },
  { compania: "La Occidental de Seguros", tipo_cobertura: "individual", edad_min: 66, edad_max: 89, suma_asegurada: 5000, prima: 275 },

  // Seguros Caracas - Individual
  { compania: "Seguros Caracas", tipo_cobertura: "individual", edad_min: 0, edad_max: 17, suma_asegurada: 5000, prima: 260 },
  { compania: "Seguros Caracas", tipo_cobertura: "individual", edad_min: 18, edad_max: 29, suma_asegurada: 5000, prima: 260 },
  { compania: "Seguros Caracas", tipo_cobertura: "individual", edad_min: 30, edad_max: 39, suma_asegurada: 5000, prima: 260 },
  { compania: "Seguros Caracas", tipo_cobertura: "individual", edad_min: 40, edad_max: 49, suma_asegurada: 5000, prima: 275 },
  { compania: "Seguros Caracas", tipo_cobertura: "individual", edad_min: 50, edad_max: 59, suma_asegurada: 5000, prima: 290 },
  { compania: "Seguros Caracas", tipo_cobertura: "individual", edad_min: 60, edad_max: 65, suma_asegurada: 5000, prima: 300 },
  { compania: "Seguros Caracas", tipo_cobertura: "individual", edad_min: 66, edad_max: 89, suma_asegurada: 5000, prima: 300 },

  // Seguros Hispanas - Individual
  { compania: "Seguros Hispanas", tipo_cobertura: "individual", edad_min: 0, edad_max: 17, suma_asegurada: 5000, prima: 245 },
  { compania: "Seguros Hispanas", tipo_cobertura: "individual", edad_min: 18, edad_max: 29, suma_asegurada: 5000, prima: 245 },
  { compania: "Seguros Hispanas", tipo_cobertura: "individual", edad_min: 30, edad_max: 39, suma_asegurada: 5000, prima: 245 },
  { compania: "Seguros Hispanas", tipo_cobertura: "individual", edad_min: 40, edad_max: 49, suma_asegurada: 5000, prima: 255 },
  { compania: "Seguros Hispanas", tipo_cobertura: "individual", edad_min: 50, edad_max: 59, suma_asegurada: 5000, prima: 270 },
  { compania: "Seguros Hispanas", tipo_cobertura: "individual", edad_min: 60, edad_max: 65, suma_asegurada: 5000, prima: 280 },
  { compania: "Seguros Hispanas", tipo_cobertura: "individual", edad_min: 66, edad_max: 89, suma_asegurada: 5000, prima: 280 }
];
